export const SET_SELECTED_DISC = 'SET_SELECTED_DISC';
export const SET_AVAILABLE_PLACES = 'SET_AVAILABLE_PLACES';
export const SET_PLAYER_TURN = 'SET_PLAYER_TURN';
export const SET_BOARD_MOV = 'SET_BOARD_MOV';
export const SET_KEEP_MOV = 'SET_KEEP_MOV';
export const SET_WHITE_POINTS = 'SET_WHITE_POINTS';
export const SET_BLACK_POINTS = 'SET_BLACK_POINTS';
export const SET_WIN_PLAYER = 'SET_WIN_PLAYER';
